### ISSUE TITLE
Method to encode from JSON to base64 Protobuf

### ISSUE THREAD

**Issue by Benjamin-Loison** [menmob/innertube-documentation#1]
In [this Wiki section](https://github.com/menmob/innertube-documentation/wiki/Decoding-Protobuf-Objects/773d12e4345bab35a14c29d3f3c10210f44def08#cyberchef) you give a method to decode a received base64 Protobuf but as I detail in [this issue](https://github.com/Benjamin-Loison/YouTube-operational-API/issues/190) I would like to write in my source code *meaningful* JSON parameters like:

```json
{
    "2": {
        "2": 1
    }
}
```

instead of the blacker box: `EgIQAQ==` but still be able to generate such base64 protobuf on the fly from above JSON. Is there any way to do so, even guessing the schema or so?

**Comment by menmob** [comment]
You can do this. I believe there is a python package called blackboxprotobuf I have used for it. Let me see if I can find a code example in a few hours.

**Comment by Benjamin-Loison** [comment]
Thank you for this reference, it seems to be quite what I was looking for.

```py
import blackboxprotobuf
import base64
import json

data = base64.b64decode('EgIQAQ==', altchars = '-_')
message, typedef = blackboxprotobuf.decode_message(data)
print(json.dumps(message, indent = 4))
print(json.dumps(typedef, indent = 4))

##

message = {
    '2': {'2': 1}
}

typedef = {
    '2': {
        'type': 'message',
        'message_typedef': {
            '2': {
                'type': 'int'
            }
        },
        'field_order': [
            ('2', 0)
        ]
    }
}

data = blackboxprotobuf.encode_message(message, typedef)
print(base64.b64encode(data, altchars = b'-_').decode('ascii'))
```
